name: walletwise
description: WalletWise - Smart Financial Management Made Simple
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  fl_chart: ^0.63.0

  firebase_core: ^2.24.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.13.0
  provider: ^6.1.5+1
  intl: ^0.19.0
  uuid: ^4.0.0

  # UI
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
